<Project>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup>
    <Product>Ledwright</Product>
    <Company>betty-crokker</Company>
    <Authors>Chris Cooper</Authors>
    <Copyright>Copyright (c) 2026 Chris Cooper</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/betty-crokker/Ledwright</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <Version>0.1.0</Version>
  </PropertyGroup>

</Project>
